### ISSUE TITLE
Kinetics results on ECO 16

### ISSUE THREAD

**Issue by yoniaflalo** [mzolfaghari/ECO-efficient-video-understanding#42]
Hi.

In the paper, it is mentioned that you get 64.4% accuracy on Kinetics database for ECO-lite 16 frame. To get this result, do you use the protocol of Kinetics evaluation, with randomly sampling clips of 16 frames from every video and averaging over the results of classification for each inference, or do you use a single inference with 16 frames randomly sampled from the 16 segments of the video? 

I tried to reproduce this results using the weights eco_lite_rgb_16F_kinetics_v3.pth.tar and I get only 58.5% on a single inference. 

Thanks

**Comment by mzolfaghari** [comment]
@yoniaflalo The results in the paper are reported based on the Caffe version but Pytorch version has slightly different results. We don't follow other papers evaluation scheme because usually they are time-consuming and does not fit to the real-time scenarios. But your results seem quite low. For the evaluation, you need to select 16 equi-distance frames with center cropping.
